import { useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
	UserViewMode,
	UserViewModeTab,
	usePostUser,
	usersQueryOptions,
} from "@/features/users";

export const Route = createFileRoute("/(app)/dashboard/users/")({
	staticData: {
		hideBreadcrumb: true,
	},
	loader: async ({ context }) => {
		await context.queryClient.ensureQueryData(usersQueryOptions);
	},
	component: UsersPage,
});

function UsersPage() {
	const usersQuery = useSuspenseQuery(usersQueryOptions);
	const users = usersQuery.data;
	const [viewMode, setViewMode] = useState<UserViewMode>(UserViewMode.LIST);

	// Example mutation usage
	const { mutate: postUser } = usePostUser();

	const demoUser = {
		id: 0, // ID is usually generated by backend
		name: "New User",
		username: "newuser",
		email: "new@example.com",
		phone: "123-456-7890",
		website: "example.com",
		address: {
			street: "123 St",
			suite: "Apt 1",
			city: "City",
			zipcode: "12345",
			geo: { lat: "0", lng: "0" },
		},
		company: { name: "Company", catchPhrase: "Phrase", bs: "bs" },
	};

	const handleSetViewMode = (viewMode: UserViewMode) => {
		setViewMode(viewMode);
	};

	return (
		<div className="space-y-4">
			<div className="flex justify-between items-center">
				<h1 className="text-2xl font-bold">Users</h1>
				<Button
					onClick={() => {
						postUser(demoUser);
					}}
				>
					Add User (Demo)
				</Button>
			</div>
			<UserViewModeTab
				users={users}
				currentViewMode={viewMode}
				onViewModeChange={handleSetViewMode}
			/>
		</div>
	);
}
