/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appDashboardUsersRouteRouteImport } from './routes/(app)/dashboard/users/route'
import { Route as appDashboardPostsRouteRouteImport } from './routes/(app)/dashboard/posts/route'
import { Route as appDashboardOverviewRouteRouteImport } from './routes/(app)/dashboard/overview/route'
import { Route as appDashboardUsersIndexRouteImport } from './routes/(app)/dashboard/users/index'
import { Route as appDashboardPostsIndexRouteImport } from './routes/(app)/dashboard/posts/index'
import { Route as appDashboardUsersUserIdRouteImport } from './routes/(app)/dashboard/users/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardUsersRouteRoute = appDashboardUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardPostsRouteRoute = appDashboardPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardOverviewRouteRoute =
  appDashboardOverviewRouteRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)
const appDashboardUsersIndexRoute = appDashboardUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardUsersRouteRoute,
} as any)
const appDashboardPostsIndexRoute = appDashboardPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardPostsRouteRoute,
} as any)
const appDashboardUsersUserIdRoute = appDashboardUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => appDashboardUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/dashboard/overview': typeof appDashboardOverviewRouteRoute
  '/dashboard/posts': typeof appDashboardPostsRouteRouteWithChildren
  '/dashboard/users': typeof appDashboardUsersRouteRouteWithChildren
  '/dashboard/': typeof appDashboardIndexRoute
  '/dashboard/users/$userId': typeof appDashboardUsersUserIdRoute
  '/dashboard/posts/': typeof appDashboardPostsIndexRoute
  '/dashboard/users/': typeof appDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/overview': typeof appDashboardOverviewRouteRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/dashboard/users/$userId': typeof appDashboardUsersUserIdRoute
  '/dashboard/posts': typeof appDashboardPostsIndexRoute
  '/dashboard/users': typeof appDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/(app)/dashboard/overview': typeof appDashboardOverviewRouteRoute
  '/(app)/dashboard/posts': typeof appDashboardPostsRouteRouteWithChildren
  '/(app)/dashboard/users': typeof appDashboardUsersRouteRouteWithChildren
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/dashboard/users/$userId': typeof appDashboardUsersUserIdRoute
  '/(app)/dashboard/posts/': typeof appDashboardPostsIndexRoute
  '/(app)/dashboard/users/': typeof appDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/overview'
    | '/dashboard/posts'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/users/$userId'
    | '/dashboard/posts/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/overview'
    | '/dashboard'
    | '/dashboard/users/$userId'
    | '/dashboard/posts'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/(app)/dashboard'
    | '/(app)/dashboard/overview'
    | '/(app)/dashboard/posts'
    | '/(app)/dashboard/users'
    | '/(app)/dashboard/'
    | '/(app)/dashboard/users/$userId'
    | '/(app)/dashboard/posts/'
    | '/(app)/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/users': {
      id: '/(app)/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof appDashboardUsersRouteRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/posts': {
      id: '/(app)/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof appDashboardPostsRouteRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/overview': {
      id: '/(app)/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof appDashboardOverviewRouteRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/users/': {
      id: '/(app)/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof appDashboardUsersIndexRouteImport
      parentRoute: typeof appDashboardUsersRouteRoute
    }
    '/(app)/dashboard/posts/': {
      id: '/(app)/dashboard/posts/'
      path: '/'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof appDashboardPostsIndexRouteImport
      parentRoute: typeof appDashboardPostsRouteRoute
    }
    '/(app)/dashboard/users/$userId': {
      id: '/(app)/dashboard/users/$userId'
      path: '/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof appDashboardUsersUserIdRouteImport
      parentRoute: typeof appDashboardUsersRouteRoute
    }
  }
}

interface appDashboardPostsRouteRouteChildren {
  appDashboardPostsIndexRoute: typeof appDashboardPostsIndexRoute
}

const appDashboardPostsRouteRouteChildren: appDashboardPostsRouteRouteChildren =
  {
    appDashboardPostsIndexRoute: appDashboardPostsIndexRoute,
  }

const appDashboardPostsRouteRouteWithChildren =
  appDashboardPostsRouteRoute._addFileChildren(
    appDashboardPostsRouteRouteChildren,
  )

interface appDashboardUsersRouteRouteChildren {
  appDashboardUsersUserIdRoute: typeof appDashboardUsersUserIdRoute
  appDashboardUsersIndexRoute: typeof appDashboardUsersIndexRoute
}

const appDashboardUsersRouteRouteChildren: appDashboardUsersRouteRouteChildren =
  {
    appDashboardUsersUserIdRoute: appDashboardUsersUserIdRoute,
    appDashboardUsersIndexRoute: appDashboardUsersIndexRoute,
  }

const appDashboardUsersRouteRouteWithChildren =
  appDashboardUsersRouteRoute._addFileChildren(
    appDashboardUsersRouteRouteChildren,
  )

interface appDashboardRouteRouteChildren {
  appDashboardOverviewRouteRoute: typeof appDashboardOverviewRouteRoute
  appDashboardPostsRouteRoute: typeof appDashboardPostsRouteRouteWithChildren
  appDashboardUsersRouteRoute: typeof appDashboardUsersRouteRouteWithChildren
  appDashboardIndexRoute: typeof appDashboardIndexRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardOverviewRouteRoute: appDashboardOverviewRouteRoute,
  appDashboardPostsRouteRoute: appDashboardPostsRouteRouteWithChildren,
  appDashboardUsersRouteRoute: appDashboardUsersRouteRouteWithChildren,
  appDashboardIndexRoute: appDashboardIndexRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
